### PR TITLE
Task 4

### PR DESCRIPTION
**Pull request by Deamon19**
DONE: task 4.1.1 ==> created two tables: products & stocks
DONE: task 4.1.2 ==> write a script to fill tables with test examples

DONE: task 4.2.1 ==> extend your serverless.yml file with data about your database
DONE: task 4.2.2 ==> integrate the getProductsList lambda with database
DONE: task 4.2.3 ==> productID implement a Product model on FE side
DONE: task 4.2.4 ==> integrate the getProductsById lambda with database

DONE: task 4.3.1 ==> create a lambda function called createProduct
DONE: task 4.3.2 ==> createProduct lambda connect with POST /products
DONE: task 4.3.3 ==> logic implemented

DONE: task 4.4==> commit all your work

Additional:
DONE: POST /products lambda functions returns error 400 status code if product data is invalid
DONE: All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
DONE: All lambdas do console.log for each incoming requests and their arguments

endpoints:
GET - https://ddg2066n9l.execute-api.eu-west-3.amazonaws.com/dev/products
GET - https://ddg2066n9l.execute-api.eu-west-3.amazonaws.com/dev/products/{productId}
POST - https://ddg2066n9l.execute-api.eu-west-3.amazonaws.com/dev/products
GET - https://ddg2066n9l.execute-api.eu-west-3.amazonaws.com/dev/products/mock (fill db with mocks)

### CODE REVIEW

**Comment by tlgadrkn** [comment]
could not see your FE application url, could you share it ?

**Comment by tlgadrkn** [comment]
also I get error when making request
image

**Comment by Deamon19** [comment]
> could not see your FE application url, could you share it ?
Link was in FE repo readme file)

https://d3epp4v29vwjz2.cloudfront.net/

**Comment by Deamon19** [comment]
> also I get error when making request image

This may happend cause of mock lambda should run first to fill db. I triggered it, now it should work

**Pull request merged**
